WebTruyen/Controllers/TrangChuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebTruyen.Controllers
{
    public class TrangChuController : Controller
    {
        // GET: TrangChu
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult NavPartial()
        {
            return View();
        }
        public ActionResult SliderPartial()
        {
            return PartialView();
        }
        public ActionResult Chitiettruyen()
        {
            return PartialView();
        }

    }
}

WebTruyen/Controllers/TruyenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebTruyen.Controllers
{
    public class TruyenController : Controller
    {
        // GET: Truyen
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebTruyen/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebTruyen/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebTruyen/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

WebTruyen/Views/Shared/FooterPartial.cshtml
<footer>
    <div class="container py-4">
        <span class="copyright">&copy; 2019 ZFCon</span>
        <span class="design float-right">Designed by ZFCon</span>
    </div>
</footer>

WebTruyen/Views/Shared/Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Manga Reader</title>

    <!-- css files -->
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.10.2/css/all.css">
   
    <link href="~/Content/css/main.css" rel="stylesheet" />

    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet" />
</head>

<body>
    <!-- start navbar -->

    @Html.Action("NavPartial", "TrangChu")

    <!-- end navbar-->
    <!-- start slider -->
    @RenderSection("slider", required: false)

    <!-- end slider -->
    <!-- start lastest -->
    @RenderBody()

    <!-- end lastest -->
    <!-- start footer -->
    @Html.Partial("FooterPartial")


    <!-- end footer -->
    <!-- js files -->

    <script src="~/Content/js/jquery-3.4.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>

    <script src="~/Content/js/bootstrap.min.js"></script>

    <script src="~/Content/js/main.js"></script>
</body>

</html>

WebTruyen/Views/TrangChu/Chitiettruyen.cshtml
@{
    ViewBag.Title = "Chitiettruyen";
    Layout = "~/Views/Shared/Layout.cshtml";
}



<div class="container my-5">
    <div class="read-intro bg-light">
        <i class="far fa-bookmark fa-3x"></i>
        <div class="row">
            <div class="cover col-*">
                <img class="shadow" src="~/img/cover1.jpg" alt="">
            </div>
            <div class="info col">
                <h2 class="head">One piece</h2>
                <table class="table table-borderless">
                    <tbody>
                        <tr>
                            <th scope="row">Genre:</th>
                            <td>Sport</td>
                        </tr>
                        <tr>
                            <th scope="row">Artist:</th>
                            <td>Jacob ZFCon</td>
                        </tr>
                        <tr>
                            <th scope="row">Update:</th>
                            <td>VOL. 125</td>
                        </tr>
                        <tr>
                            <th scope="row">Rating:</th>
                            <td>
                                <i class="fa fa-star fa-2x"></i><i class="fa fa-star fa-2x"></i><i class="fa fa-star fa-2x"></i><i class="fa fa-star fa-2x"></i><i class="fa fa-star-half-alt fa-2x"></i> <span class="font-weight-bold ml-3">(10/9)</span>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <p>
                    Extended kindness trifling remember he confined outlived if.
                    Assistance sentiments yet unpleasing say. Open they an busy they my such high.
                    An active dinner wishes at unable hardly no talked on.
                    Immediate him her resolving his favourite. Wished denote abroad at branch at. <a href="#">
                        Read
                        More...
                    </a>
                </p>
            </div>
        </div>
        <div class="row">
            <a class="btn btn-red my-3 mx-1 px-5" href="#">Start reading VOL. 1</a>
        </div>
    </div>
</div>
<!-- end reading intro -->
<!-- start intro lists -->
<div class="container my-5 bg-white">
    <div class="intro-lists">
        <div class="head-list row bg-light">
            <ul class="list-unstyled list-inline">
                <li class="list-inline-item"><a data-toggle="tab" class="active" href="#ch">Ch.</a></li>
                <li class="list-inline-item"><a data-toggle="tab" href="#vol">VOL.</a></li>
                <li class="list-inline-item"><a data-toggle="tab" href="#related">Related</a></li>
                <li class="list-inline-item"><a data-toggle="tab" href="#gallery">Gallery</a></li>
            </ul>
        </div>
        <div class="tab-content">

            <!-- start ch -->
            <div id="ch" class="tab-pane fade in active show">
                <div class="row">
                    <table class="table table-striped">
                        <tbody>
                            <tr>
                                <th><a href="details.html">CH. 1, Luffy in the island with two nigga</a></th>
                                <td class="text-muted text-uppercase float-right">8 hours ago</td>
                            </tr>
                            <tr>
                                <th><a href="details.html">CH. 2, Luffy in the garden with two nigga</a></th>
                                <td class="text-muted text-uppercase float-right">8 hours ago</td>
                            </tr>
                            <tr>
                                <th><a href="details.html">Ch. 3, Luffy in the school with two nigga</a></th>
                                <td class="text-muted text-uppercase float-right">8 hours ago</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- end ch -->
            <!-- start vol -->
            <div id="vol" class="tab-pane fade">
                <div class="row">
                    <table class="table table-striped">
                        <tbody>
                            <tr>
                                <th><a href="details.html">VOL. 2, Luffy in the island</a></th>
                                <td class="text-muted text-uppercase float-right">8 hours ago</td>
                            </tr>
                            <tr>
                                <th><a href="details.html">VOL. 2, Luffy in the garden</a></th>
                                <td class="text-muted text-uppercase float-right">8 hours ago</td>
                            </tr>
                            <tr>
                                <th><a href="details.html">VOL. 3, Luffy in the school</a></th>
                                <td class="text-muted text-uppercase float-right">8 hours ago</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- end vol -->
            <!-- start related -->
            <div id="related" class="tab-pane fade">
                <div class="row">
                    <div class="col-lg-3 col-md-4 col-sm-6">
                        <a href="details.html">
                            <div class="card mb-3">
                                <img src="img/cover2.jpg" class="card-img-top" alt="">
                                <div class="card-body">
                                    <h5 class="card-title">One piece</h5>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-3 col-md-4 col-sm-6">
                        <a href="details.html">
                            <div class="card mb-3">
                                <img src="img/cover2.jpg" class="card-img-top" alt="">
                                <div class="card-body">
                                    <h5 class="card-title">One piece</h5>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-3 col-md-4 col-sm-6">
                        <a href="details.html">
                            <div class="card mb-3">
                                <img src="img/cover2.jpg" class="card-img-top" alt="">
                                <div class="card-body">
                                    <h5 class="card-title">One piece</h5>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-3 col-md-4 col-sm-6">
                        <a href="details.html">
                            <div class="card mb-3">
                                <img src="img/cover2.jpg" class="card-img-top" alt="">
                                <div class="card-body">
                                    <h5 class="card-title">One piece</h5>
                                </div>
                            </div>
                        </a>
                    </div>

                </div>
            </div>
            <!-- end related -->
            <!-- start gallery -->
            <div id="gallery" class="tab-pane fade">
                <div class="imgrow">
                    <div class="imgcol">
                        <img src="img/cover1.jpg" width="100%">
                        <img src="img/slider1.jpg" width="100%">
                        <img src="img/apex-section-bg-legends-caustic-xl.jpg.adapt.320w.jpg" width="100%">

                    </div>
                    <div class="imgcol">
                        <img src="img/76693209_2445782385645459_1824072803884728320_n.jpg" width="100%">
                        <img src="img/slider1.jpg" width="100%">
                        <img src="img/cover4.jpg" width="100%">
                    </div>
                    <div class="imgcol">
                        <img src="img/72561095_1152623741615641_762555470421426176.jpg" width="100%">
                        <img src="img/47126346_671615859906817_766212574944428032_n.jpg" width="100%">
                        <img src="img/cover2.jpg" width="100%">
                    </div>
                </div>
            </div>
            <!-- end gallery-->

        </div>
    </div>
</div>

WebTruyen/Views/TrangChu/Index.cshtml
//aaa
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}
@section slider{
    @Html.Action("SliderPartial", "TrangChu")
}
<div class="lastest container mt-4 mt-sm-5">
    <div class="row text-center">
        <div class="col-lg-6">
            <h2 class="font-weight-bolder float-left">Lastest Manga Updates</h2>
        </div>

    </div>

    <div class="posts row">
        <div class="col-lg-2 col-md-3 col-sm-4">
            <div class="card mb-3">
                <a href="details.html"><img src="~/img/cover1.jpg" class="card-img-top" alt=""></a>
                <div class="over text-center">
                    <div class="head text-left">
                        <h6>One Piece</h6>
                    </div>
                    <div class="about-list">
                        <table class="table table-borderless">
                            <tbody>
                                <tr>
                                    <th scope="row">Genre:</th>
                                    <td>Sport</td>
                                </tr>
                                <tr>
                                    <th scope="row">Artist:</th>
                                    <td>Jacob ZFCon</td>
                                </tr>
                                <tr>
                                    <th scope="row">Update:</th>
                                    <td>VOL. 125</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <p class="about text-muted">
                        efficitur eu tortor. Nam et odio aliquet.
                    </p>
                    <a class="reading btn" href="details.html">Start reading VOL. 1</a>
                </div>
                <div class="card-body">
                    <h5 class="card-title"><a href="details.html">One Piece</a></h5>
                    <p class="card-text">CH. 2</p>
                    <p class="card-text"><small class="text-muted text-uppercase">Update 1 Hour ago</small></p>
                </div>
            </div>
        </div>


        <div class="col-lg-2 col-md-3 col-sm-4">
            <div class="card mb-3">
                <a href="details.html"><img src="~/img/cover2.jpg" class="card-img-top" alt=""></a>
                <div class="over text-center">
                    <div class="head text-left">
                        <h6>One Piece</h6>
                    </div>
                    <div class="about-list">
                        <table class="table table-borderless">
                            <tbody>
                                <tr>
                                    <th scope="row">Genre:</th>
                                    <td>Sport</td>
                                </tr>
                                <tr>
                                    <th scope="row">Artist:</th>
                                    <td>Jacob ZFCon</td>
                                </tr>
                                <tr>
                                    <th scope="row">Update:</th>
                                    <td>VOL. 125</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <p class="about text-muted">
                        efficitur eu tortor. Nam et odio aliquet.
                    </p>
                    <a class="reading btn" href="details.html">Start reading VOL. 1</a>
                </div>
                <div class="card-body">
                    <h5 class="card-title"><a href="details.html">One Piece</a></h5>
                    <p class="card-text">CH. 2</p>
                    <p class="card-text"><small class="text-muted text-uppercase">Update 1 Hour ago</small></p>
                </div>
            </div>
        </div>
    </div>
</div>

WebTruyen/Views/TrangChu/NavPartial.cshtml
<nav class="navbar navbar-expand-lg navbar-light shadow py-2 py-sm-0">
    <a class="navbar-brand" href="#">
        <h5>Manga Man</h5>
    </a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="container-fluid">
            <div class="row py-3">
                <div class="col-lg-6 col-sm-12 mb-3 mb-sm-0">
                    <ul class="navbar-nav mr-auto">
                        <!-- always use single word for li -->
                        <li class="nav-item active">
                            <a class="nav-link" href="#">Home<span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">New</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Populer</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Browse
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Something else here</a>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="col">
                    <form class="form-inline search">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Type Title, auther or genre"
                                   aria-label="Type Title, auther or genre">
                            <div class="input-group-append">
                                <button class="btn btn-outline-secondary" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="profile float-right">
        <div class="saved">
            <button class="btn" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">
                <i class="fa fa-bookmark fa-2x"></i>
            </button>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="#">
                    <div class="row">
                        <div class="col"><img src="img/cover1.jpg" width="50"></div>
                        <div class="col">
                            <h5>One piece 1</h5>
                            <small>Lastest <span>VOL. 11</span></small>
                        </div>
                    </div>
                </a>
                <a class="dropdown-item" href="#">
                    <div class="row">
                        <div class="col"><img src="img/cover1.jpg" width="50"></div>
                        <div class="col">
                            <h5>One piece 1</h5>
                            <small>Lastest <span>VOL. 11</span></small>
                        </div>
                    </div>
                </a>
                <hr>
                <a class="dropdown-item" href="#">View all saved mangas (14)</a>
            </div>
        </div>
        <div class="account">
            <button class="btn" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">
                <i class="fa fa-user-circle fa-2x"></i><i class="fa fa-angle-down"></i>
            </button>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="#">My account</a>
                <a class="dropdown-item" href="#">logout</a>
            </div>
        </div>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
</nav>

WebTruyen/Views/TrangChu/SliderPartial.cshtml
<div id="mangaslider" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="~/img/slider1.jpg" alt="First slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="~/img/slider2.jpg" alt="Second slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="~/img/slider3.jpg" alt="Third slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#mangaslider" role="button" data-slide="prev">
        <div><span class="carousel-control-prev-icon" aria-hidden="true"></span></div>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#mangaslider" role="button" data-slide="next">
        <div><span class="carousel-control-next-icon" aria-hidden="true"></span></div>
        <span class="sr-only">Next</span>
    </a>
</div>

WebTruyen/Views/Truyen/Index.cshtml
<!-- Head -->
<head>
    <meta charset="utf-8" />
    <title>Sin titulo</title>
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" />
    <link href="~/Content/css/black-3d-1.css" rel="stylesheet" />

    <link href="~/Content/css/skin.css" rel="stylesheet" />

    <link href="~/Content/css/loading.css" rel="stylesheet" />

    <link href="~/Content/css/custom.css" rel="stylesheet" />
</head>
<!-- End of Head -->
<!-- Body -->
<body onload="load()" onresize="mutate()">
    <noscript>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="alert alert-danger">
                        <span class="glyphicon glyphicon-exclamation-sign"></span>&nbsp;<strong>Error</strong>
                        Parece que Javascript no esta habilitado en tu
                        navegador. Habilitalo y recarga la p&aacute;gina.
                    </div>
                </div>
            </div>
        </div>
    </noscript>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button"
                        class="navbar-toggle collapsed"
                        data-toggle="collapse"
                        data-target="#collapsable-content"
                        aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand"
                   href="#"
                   data-toggle="modal"
                   data-target="#about-modal">Manga Reader</a>
            </div>
            <div class="collapse navbar-collapse" id="collapsable-content">
                <ul class="nav navbar-nav" id="first-navbar-section">
                    <li data-toggle="tooltip"
                        data-placement="bottom"
                        title="Primera p&aacute;gina">
                        <a href="javascript:void(0)"
                           onclick="firstPage()"
                           id="rw">
                            <span class="glyphicon glyphicon-fast-backward"></span>
                        </a>
                    </li>
                    <li data-toggle="tooltip"
                        data-placement="bottom"
                        title="P&aacute;gina anterior">
                        <a href="javascript:void(0)"
                           onclick="backward()"
                           id="b">
                            <span class="glyphicon glyphicon-backward"></span>
                        </a>
                    </li>
                    <li data-toggle="tooltip"
                        data-placement="bottom"
                        title="P&aacute;gina siguiente">
                        <a href="javascript:void(0)"
                           onclick="forward()"
                           id="f">
                            <span class="glyphicon glyphicon-forward"></span>
                        </a>
                    </li>
                    <li data-toggle="tooltip"
                        data-placement="bottom"
                        title="&Uacute;ltima p&aacute;gina">
                        <a href="javascript:void(0)"
                           onclick="lastPage()"
                           id="ff">
                            <span class="glyphicon glyphicon-fast-forward"></span>
                        </a>
                    </li>
                    <li>
                        <table>
                            <tr>
                                <td>
                                    <p class="navbar-text special-margin">
                                        <strong>Ir a:</strong>
                                    </p>
                                </td>
                                <td>
                                    <div class="black-select">
                                        <select id="page-selector"
                                                onchange="pageSelector()"></select>
                                    </div>
                                </td>
                            </tr>
                        </table>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li id="manga-title">
                        <p class="navbar-text">T&iacute;tulo</p>
                    </li>
                    <li id="page-counter">
                        <p class="navbar-text">P&aacute;gina X de Y</p>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <div class="row">
            <div class="col-md-offset-1 col-md-10" id="main-screen">
                <div id="cover-spin"></div>
            </div>
        </div>

        <!-- Modal (About) -->
        <div class="modal fade" role="dialog" id="about-modal">
            <div class="modal-dialog modal-sm" role="document">
                <div class="modal-content">
                    <div class="modal-header black-3d-1">
                        <button type="button"
                                class="close"
                                data-dismiss="modal">
                            &times;
                        </button>
                        <h4 class="modal-title">Acerca de</h4>
                    </div>
                    <div class="modal-body">
                        <p class="text-left">
                            Lector de Mangas creado por
                            <strong>
                                Cristian Jos&eacute; Jim&eacute;nez
                                Diazgranados
                            </strong>
                            para
                            <i id="host-name">&lt;tu_pagina_aqui&gt;</i>
                        </p>
                        <p class="text-center" id="copyright">
                            &copy;2016-2019
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <!-- End of modal -->
    </div>

    <script type="text/javascript"
            language="javascript"
            src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script type="text/javascript"
            language="javascript"
            src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


    <script src="~/Content/js/bootstrap.min.js"></script>
    <script src="~/Content/js/constants.js"></script>
    <script src="~/Content/js/context.js"></script>
    <script src="~/Content/js/core.js"></script>
    <script src="~/Content/js/evolution.js"></script>
    <script src="~/Content/js/getters.js"></script>
    <script src="~/Content/js/jquery-3.4.1.min.js"></script>
    <script src="~/Content/js/limits.js"></script>
    <script src="~/Content/js/loader.js"></script>
    <script src="~/Content/js/locale.js"></script>
    <script src="~/Content/js/main.js"></script>
    <script src="~/Content/js/maker.js"></script>
    <script src="~/Content/js/switches.js"></script>
    <script src="~/Content/js/util.js"></script>
    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
</body>
<!-- End of Body -->